<?php

// config/auth_permissions.php
return [
    // Senha para registro administrativo
    'admin_registration_password' => env('ADMIN_REGISTRATION_PASSWORD', 'admin2024!'),
    
    // Configurações de permissões por role
    'role_permissions' => [
        'admin' => [
            'view_dashboard',
            'view_reports',
            'export_reports',
            'manage_users',
            'create_users',
            'edit_users',
            'delete_users',
            'activate_users',
            'manage_products',
            'create_products',
            'edit_products',
            'delete_products',
            'adjust_stock',
            'manage_categories',
            'create_categories',
            'edit_categories',
            'delete_categories',
            'view_sales',
            'create_sales',
            'edit_sales',
            'delete_sales',
            'manage_orders',
            'create_orders',
            'edit_orders',
            'delete_orders',
            'convert_orders',
            'manage_debts',
            'create_debts',
            'edit_debts',
            'delete_debts',
            'cancel_debts',
            'manage_payments',
            'manage_expenses',
            'create_expenses',
            'edit_expenses',
            'delete_expenses',
            'view_finances',
            'manage_finances',
            'manage_stock',
            'view_stock_movements',
            'create_stock_movements',
            'manage_settings',
            'backup_system',
            'view_logs',
        ],
        
        'manager' => [
            'view_dashboard',
            'view_reports',
            'export_reports',
            'view_products',
            'create_products',
            'edit_products',
            'adjust_stock',
            'manage_categories',
            'view_categories',
            'create_categories',
            'edit_categories',
            'view_sales',
            'create_sales',
            'edit_sales',
            'view_orders',
            'create_orders',
            'edit_orders',
            'convert_orders',
            'view_debts',
            'create_debts',
            'edit_debts',
            'manage_payments',
            'view_expenses',
            'create_expenses',
            'edit_expenses',
            'view_finances',
            'manage_finances',
            'manage_stock',
            'view_stock_movements',
            'create_stock_movements',
        ],

        'stock_manager' => [
            'view_dashboard',
            'view_products',
            'create_products',
            'edit_products',
            'adjust_stock',
            'manage_categories',
            'view_categories',
            'create_categories',
            'edit_categories',
            'manage_stock',
            'view_stock_movements',
            'create_stock_movements',
            'view_expenses',
            'create_expenses',
        ],

        'cashier' => [
            'view_dashboard',
            'view_sales',
            'create_sales',
            'view_products',
            'view_debts',
            'create_debts',
            'manage_payments',
            'view_orders',
            'create_orders',
            'view_stock_movements',
        ],
        
        'staff' => [
            'view_dashboard',
            'view_products',
            'view_sales',
            'create_sales',
            'view_orders',
            'create_orders',
            'view_stock_movements',
        ],
    ],
    
    // Lista de todas as permissões disponíveis no sistema com descrições amigáveis
    'all_permissions' => [
        'view_dashboard'        => 'Visualizar Dashboard',
        'view_reports'          => 'Visualizar Relatórios',
        'export_reports'        => 'Exportar Relatórios',
        'manage_users'          => 'Gerir Usuários e Funcionários',
        'create_users'          => 'Criar Usuários',
        'edit_users'            => 'Editar Usuários',
        'delete_users'          => 'Excluir Usuários',
        'activate_users'        => 'Ativar/Desativar Usuários',
        'view_products'         => 'Visualizar Produtos',
        'manage_products'       => 'Gerir Produtos',
        'create_products'       => 'Criar Produtos',
        'edit_products'         => 'Editar Produtos',
        'delete_products'       => 'Excluir Produtos',
        'adjust_stock'          => 'Ajustar Stock',
        'view_categories'       => 'Visualizar Categorias',
        'manage_categories'     => 'Gerir Categorias',
        'create_categories'     => 'Criar Categorias',
        'edit_categories'       => 'Editar Categorias',
        'delete_categories'     => 'Excluir Categorias',
        'view_sales'            => 'Visualizar Vendas',
        'create_sales'          => 'Criar Vendas (POS)',
        'edit_sales'            => 'Editar Vendas',
        'delete_sales'          => 'Excluir Vendas',
        'view_orders'           => 'Visualizar Pedidos',
        'manage_orders'         => 'Gerir Pedidos',
        'create_orders'         => 'Criar Pedidos',
        'edit_orders'           => 'Editar Pedidos',
        'delete_orders'         => 'Excluir Pedidos',
        'convert_orders'        => 'Converter Pedidos',
        'view_debts'            => 'Visualizar Dívidas',
        'manage_debts'          => 'Gerir Dívidas',
        'create_debts'          => 'Criar Dívidas',
        'edit_debts'            => 'Editar Dívidas',
        'delete_debts'          => 'Excluir Dívidas',
        'cancel_debts'          => 'Cancelar Dívidas',
        'manage_payments'       => 'Registrar Pagamentos de Dívida',
        'view_expenses'         => 'Visualizar Despesas',
        'manage_expenses'       => 'Gerir Despesas',
        'create_expenses'       => 'Criar Despesas',
        'edit_expenses'         => 'Editar Despesas',
        'delete_expenses'       => 'Excluir Despesas',
        'view_finances'         => 'Visualizar Finanças',
        'manage_finances'       => 'Gerir Finanças/Caixa',
        'manage_stock'          => 'Gerir Stock Global',
        'view_stock_movements'  => 'Visualizar Movimentações de Stock',
        'create_stock_movements'=> 'Criar Movimentações de Stock',
        'manage_settings'       => 'Gerir Configurações do Sistema',
        'backup_system'         => 'Realizar Backups',
        'view_logs'             => 'Visualizar Logs de Auditoria',
    ],

    // Menu items configuration
    'menu_items' => [
        'dashboard' => ['icon' => 'fa-tachometer-alt', 'permission' => 'view_dashboard'],
        'pos' => ['icon' => 'fa-cash-register', 'permission' => 'create_sales'],
        'products' => ['icon' => 'fa-box', 'permission' => 'view_products'],
        'categories' => ['icon' => 'fa-tags', 'permission' => 'view_categories'],
        'orders' => ['icon' => 'fa-clipboard-list', 'permission' => 'view_orders'],
        'sales' => ['icon' => 'fa-shopping-cart', 'permission' => 'view_sales'],
        'debts' => ['icon' => 'fa-credit-card', 'permission' => 'view_debts'],
        'expenses' => ['icon' => 'fa-receipt', 'permission' => 'view_expenses'],
        'finances' => ['icon' => 'fa-wallet', 'permission' => 'view_finances'],
        'stock' => ['icon' => 'fa-exchange-alt', 'permission' => 'view_stock_movements'],
        'reports' => ['icon' => 'fa-chart-bar', 'permission' => 'view_reports'],
        'users' => ['icon' => 'fa-users', 'permission' => 'manage_users', 'admin_only' => true],
        'profile' => ['icon' => 'fa-user-cog', 'permission' => null],
        'settings' => ['icon' => 'fa-cog', 'permission' => 'manage_settings', 'admin_only' => true],
    ]
];

